#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(25, "kalloctest")
def test_kalloctest():
    r.run_qemu(shell_script([
        'kalloctest'
    ]), timeout=900)
    r.match(
        r'^test1 OK$',
        r'^test2 OK$',
        r'^test3 OK$',
        no=[
            r'FAIL',
            r'panic:',
            r'unexpected scause'
        ]
    )

@test(25, "usertests -q")
def test_usertests_q():
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=900)
    r.match(
        r'^ALL TESTS PASSED$',
        no=[
            r'^FAILED$',
            r'^SOME TESTS FAILED$',
            r'panic:',
            r'unexpected scause'
        ]
    )

run_tests()
